import type { EmailAccount, Message } from "@/core/types";

const now = Date.now();
const min = 60 * 1000;
const hour = 60 * min;

export const DEMO_ACCOUNTS: readonly EmailAccount[] = [
  { id: "acc-personal", address: "joseph@proton.me", displayName: "Personal", provider: "mock" },
  { id: "acc-work", address: "joseph.k@outlook.com", displayName: "Work", provider: "mock" },
];

let seq = 0;
function msg(m: Omit<Message, "id">): Message {
  return { id: `msg-${seq++}`, ...m };
}

export const DEMO_MESSAGES: readonly Message[] = [
  msg({
    accountId: "acc-work",
    sender: "GitHub",
    senderAddress: "noreply@github.com",
    subject: "[nexus] CI pipeline failed on main",
    preview: "The workflow 'build-and-test' failed for commit a1f9c3…",
    body: "The workflow 'build-and-test' failed for commit a1f9c3.\n\nView the run for details. This is an automated notification.",
    timestamp: now - 22 * min,
    read: false,
    archived: false,
    category: "important",
    canUnsubscribe: false,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Steam",
    senderAddress: "noreply@steampowered.com",
    subject: "Your Steam account: new purchase receipt",
    preview: "Thank you for your purchase. Order total: $59.99…",
    body: "Thank you for your purchase.\n\nHelldivers 2 — $39.99\nOrder total: $39.99\n\nThis is your receipt.",
    timestamp: now - 2 * hour,
    read: false,
    archived: false,
    category: "receipt",
    canUnsubscribe: false,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Larian Studios",
    senderAddress: "news@larian.com",
    subject: "Patch 8 is here — new subclasses await",
    preview: "The biggest update yet for Baldur's Gate 3 brings 12 new subclasses…",
    body: "The biggest update yet for Baldur's Gate 3 brings 12 new subclasses, cross-play, and photo mode.",
    timestamp: now - 5 * hour,
    read: false,
    archived: false,
    category: "newsletter",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-work",
    sender: "Linear",
    senderAddress: "notifications@linear.app",
    subject: "3 issues assigned to you are due this week",
    preview: "NEX-42, NEX-51 and NEX-58 are approaching their due dates…",
    body: "NEX-42 Storage analyzer drill-down\nNEX-51 Privacy hotkey handler\nNEX-58 Steam provider stub",
    timestamp: now - 8 * hour,
    read: false,
    archived: false,
    category: "important",
    canUnsubscribe: false,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Proton",
    senderAddress: "security@proton.me",
    subject: "New sign-in to your account",
    preview: "We noticed a new sign-in from a Windows device…",
    body: "We noticed a new sign-in from a Windows device in your region. If this was you, no action is needed.",
    timestamp: now - 11 * hour,
    read: false,
    archived: false,
    category: "important",
    canUnsubscribe: false,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Humble Bundle",
    senderAddress: "hello@humblebundle.com",
    subject: "New bundle: Build Your Own Indie Collection",
    preview: "Pay what you want for 10 award-winning indie games…",
    body: "Pay what you want for 10 award-winning indie games and support charity.",
    timestamp: now - 14 * hour,
    read: true,
    archived: false,
    category: "newsletter",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-work",
    sender: "Vercel",
    senderAddress: "notifications@vercel.com",
    subject: "Your subscription renews in 3 days",
    preview: "Your Pro plan ($20/mo) will renew automatically…",
    body: "Your Pro plan ($20/mo) will renew automatically on the 29th.",
    timestamp: now - 20 * hour,
    read: true,
    archived: false,
    category: "subscription",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Discord",
    senderAddress: "noreply@discord.com",
    subject: "You have 4 unread mentions in 'Co-op Night'",
    preview: "Alex: are we running We Were Here Too tonight?…",
    body: "Alex: are we running We Were Here Too tonight?\nSam: I'm down after 9\nAlex: bet",
    timestamp: now - 26 * hour,
    read: true,
    archived: false,
    category: "social",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Epic Games",
    senderAddress: "help@epicgames.com",
    subject: "This week's free game is available now",
    preview: "Claim your free game before the offer ends…",
    body: "Claim your free game before the offer ends Thursday.",
    timestamp: now - 32 * hour,
    read: true,
    archived: false,
    category: "newsletter",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-work",
    sender: "1Password",
    senderAddress: "support@1password.com",
    subject: "Watchtower: 2 passwords need attention",
    preview: "We found 2 reused passwords in your vault…",
    body: "We found 2 reused passwords in your vault. Consider updating them.",
    timestamp: now - 40 * hour,
    read: true,
    archived: false,
    category: "important",
    canUnsubscribe: false,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Amazon",
    senderAddress: "auto-confirm@amazon.com",
    subject: "Your order has shipped",
    preview: "Arriving tomorrow: Mechanical Keyboard…",
    body: "Arriving tomorrow: Mechanical Keyboard (Tactile Brown).",
    timestamp: now - 48 * hour,
    read: true,
    archived: false,
    category: "receipt",
    canUnsubscribe: false,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Medium Daily Digest",
    senderAddress: "noreply@medium.com",
    subject: "Stories for Joseph — Rust, Tauri, and desktop UX",
    preview: "Building native-feeling desktop apps in 2026…",
    body: "Building native-feeling desktop apps in 2026 and other stories curated for you.",
    timestamp: now - 52 * hour,
    read: true,
    archived: false,
    category: "newsletter",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-work",
    sender: "Notion",
    senderAddress: "team@notion.so",
    subject: "Weekly workspace summary",
    preview: "You edited 14 pages and completed 9 tasks this week…",
    body: "You edited 14 pages and completed 9 tasks this week. Nice momentum.",
    timestamp: now - 60 * hour,
    read: true,
    archived: false,
    category: "other",
    canUnsubscribe: true,
  }),
  msg({
    accountId: "acc-personal",
    sender: "Spotify",
    senderAddress: "no-reply@spotify.com",
    subject: "Your Premium receipt",
    preview: "Spotify Premium — $11.99…",
    body: "Spotify Premium — $11.99. Thanks for listening.",
    timestamp: now - 72 * hour,
    read: true,
    archived: false,
    category: "receipt",
    canUnsubscribe: false,
  }),
];
