/**
 * Synthetic, non-private test videos generated by scripts/gen-fixtures.mjs.
 * Dev builds only: served through Vite's /@fs/ from scripts/.fixtures.
 */
export interface FixtureVideo {
  readonly name: string;
  readonly width: number;
  readonly height: number;
  readonly seconds: number;
}

export const FIXTURE_VIDEOS: readonly FixtureVideo[] = [
  { name: "landscape-a", width: 640, height: 360, seconds: 24 },
  { name: "landscape-b", width: 640, height: 360, seconds: 18 },
  { name: "portrait", width: 360, height: 640, seconds: 20 },
  { name: "square", width: 480, height: 480, seconds: 16 },
  { name: "ultrawide", width: 840, height: 360, seconds: 22 },
  { name: "landscape-c", width: 640, height: 360, seconds: 30 },
];

export function fixturesAvailable(): boolean {
  return typeof __NEXUS_DEV_ROOT__ === "string" && __NEXUS_DEV_ROOT__.length > 0 && import.meta.env.DEV;
}

export function fixtureUrl(name: string): string {
  return `/@fs/${__NEXUS_DEV_ROOT__}/scripts/.fixtures/${name}.webm`;
}
